### PR TITLE
Filter domains

### PR DESCRIPTION
**Pull request by Pixelguymm**
This is a possible way to find and check full domains, without (hopefully) creating any false positives. Feel free to decline if you want, this is just my approach.

### CODE REVIEW

**Review by nikolaischunk — CHANGES_REQUESTED** [review]
Please pull latest main

**Comment by nikolaischunk** [comment]
Pretty sure your RegEx is not working

**Comment by Pixelguymm** [comment]
It worked in my application, what's wrong with it? Is it the fact that it requires `http(s)://` to work?
Also, I'll go ahead and pull the updated main in a bit.

**Comment by nikolaischunk** [comment]
>Is it the fact that it requires http(s):// to work?
Pretty sure thats it. can you remove that?

**Comment by Pixelguymm** [comment]
Sure. I added it as a way to only detect what discord would parse as a URL, but if you'd like it to be more sensitive I can certainly do that.

**Comment by Pixelguymm** [comment]
Actually, now that I'm looking at the list again, I see it also includes some `bit.ly` links. Those would never get flagged using my current approach, since I filter out only the domain.
I'll try to come up with a different approach that includes them as well.

**Pull request closed without merging**
