### PR TITLE
Match domains in the message and prevent false positives.

### PR DESCRIPTION
**Pull request by lucapolesel**
Match all the domains from the string and check if they end with one of the flagged domains.
This allows us to includes domains like 'discordapp.co'.
This is an initial PR the strings also include sub domains and an exact match would be better instead of checking that their end matches.
We should probably just get the second level + top level and do an exact match of it or include all the sub domains in the list.

### CODE REVIEW

**Comment by nikolaischunk** [comment]
uhh intresting!
sure that this matches all the domains that we have in the links repo?

**Comment by nikolaischunk** [comment]
@lucapolesel

**Comment by lucapolesel** [comment]
@nikolaischunk I have updated the description of the PR yesterday.
I think that the regex should be adjusted and then do an exact match of the matched domain since there are some addresses with the path as well (also there is one that is missing the top level domain).
I'll update it once I have some time.

**Comment by lucapolesel** [comment]
@nikolaischunk This is my current solution and I will test it a bit more.
It works with all the domains in the list except the "nitro-discordapp" one that is missing the top level domain.
I don't think that it is worth considering something like this.
I would just add it with its top level domains in the list instead.
What do you think?

**Comment by nikolaischunk** [comment]
the domain withour tld was probably added on accident, ill add the tld asap back.

**Comment by nikolaischunk** [comment]
not quite sure abt your regex, does it also detect strings in texts that dont have a `https:// ` in front?

- `https://foo.gg` should get detected
- `foo.gg` should get detected
- `foo.gg/hujdkhfjdsnf` should get detected
etc

**Comment by lucapolesel** [comment]
Yeah, http(s) and www. are optional.
You can test it here: https://regex101.com/r/wVhhvT/1

**Comment by nikolaischunk** [comment]
this is fire!!

**Pull request merged**
